In [1]:
import numpy as np

In [2]:
array_1 = np.arange(15)

In [3]:
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
#sqaureroot of every number
np.sqrt(array_1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [5]:
#exponential of every number
np.exp(array_1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06])

In [6]:
#bringing random numbers in our array
np.random.randn(10)

array([ 0.89379432, -1.03301305,  0.05395705, -1.11454896, -1.17847223,
       -0.43479751, -0.34834064, -0.790173  ,  0.2853963 , -1.69812554])

In [7]:
A = np.random.randn(10)
A

array([ 0.52091629,  0.4953063 ,  0.62747549, -0.80143043,  1.06253327,
        0.85342826, -1.11268471, -1.1440167 ,  1.31312372,  0.15067632])

In [11]:
B = np.random.randn(10)
B

array([-0.74599463, -1.95438612,  1.61533966,  1.15834845,  0.74199316,
       -0.01636729,  2.27656717, -0.42210792,  1.21356651,  0.56717183])

In [12]:
#binary functions between different arrays
np.add(A,B)

array([-0.22507834, -1.45907982,  2.24281515,  0.35691802,  1.80452643,
        0.83706097,  1.16388245, -1.56612462,  2.52669022,  0.71784815])

In [13]:
np.maximum(A,B)

array([ 0.52091629,  0.4953063 ,  1.61533966,  1.15834845,  1.06253327,
        0.85342826,  2.27656717, -0.42210792,  1.31312372,  0.56717183])

In [14]:
Website = "https://www.udemy.com/course/learning-python-for-data-analysis-and-visualization/learn/lecture/2487462?start=15#overview"
import webbrowser
webbrowser.open(Website)

True